kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: phpsvc
spec:
  replicas: 1
  template:
    metadata:
      name: phpsvc
      labels:
        app: phpsvc
    spec:
      containers:
        - image: app:1
          name: app
          resources:
            requests:
              cpu: "150m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "300Mi"