apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: phpsvc
spec:
  maxReplicas: 10
  minReplicas: 1                      
  metrics:                         
  - type: Resource
    resource:                              
      name: cpu                          
      targetAverageUtilization: 30    
  scaleTargetRef:                          
    apiVersion: extensions/v1beta1     
    kind: Deployment                       
    name: phpsvc